# Generated by Django 3.2.4 on 2023-09-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cpic',
            field=models.ImageField(null=True, upload_to='static/category/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
