# Generated by Django 3.2.4 on 2023-09-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_myorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
