# Generated by Django 3.2.4 on 2023-09-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_myorder_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='myorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, null=True)),
                ('product_name', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('product_picture', models.CharField(max_length=300, null=True)),
                ('pw', models.CharField(max_length=300, null=True)),
                ('order_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='myorder',
        ),
    ]
